export const projectinformation = [
    {
        imageURL: "",
        demoURL: "",
        githubURL: "https://github.com/tonstey/recipe-recommender",
        name: "Receipt",
        date: "",
        type: "none",
        languages: ["HTML", "CSS", "JavaScript", "ReactJS", "Tailwind", "Redux", "Django", "SQLite"],
        description: "HII",
    },
    {
        imageURL: "",
        demoURL: "",
        githubURL: "https://github.com/tonstey/e-commerce",
        name: "VelmaeMart",
        date: "Jan 2025",
        type: "Software Development",
        languages: ["MongoDB", "Express", "ReactJS", "React Router DOM","NodeJS", "Tailwind", "Zustand", "AWS S3"],
        description: "A full stack e-commerce website with user signup and login with authentication. Users can search by category, add items to cart, and imitate checkout. The website also includes a dashboard for the admin to manage products and orders. Product images are stored in AWS S3.",
    },
    {
        imageURL: "",
        demoURL: "https://github.com/tonstey/COGS108_Data_Science_Project",
        githubURL: "https://github.com/tonstey/COGS108_Data_Science_Project",
        name: "Factors  Affecting Student Grades",
        date: "Dec 2024",
        type: "Data Science",
        languages: ["Python", "Pandas", "NumPy", "Scikit-Learn", "Matplotlib", "Seaborn", "statsmodels"],
        description: "A data science project that analyzes the relationship between personal and academic factors, such as family relationships or number of school absences, to grades. The data, which is from a Kaggle dataset, is analyzed using statistical methods and visualizations.",
    },
    {
        imageURL: "",
        demoURL: "",
        githubURL: "https://github.com/tonstey/weather-app",
        name: "Weather Wise",
        date: "Aug 2024",
        type: "Software Development",
        languages: ["HTML", "CSS", "JavaScript", "ReactJS", "Tailwind", "Redux"],
        description: "A weather app that fetches weather data from an API and displays it to the user. It also includes a search bar for the user to search for a specific location. This app uses local storage to store the user's desired locations.",
    },
    {
        imageURL: "project_images/quizzical.png",
        demoURL: "https://tonstey.github.io/quizzical/",
        githubURL: "https://github.com/tonstey/quizzical",
        name: "Quizzical",
        date: "Jul 2024",
        type: "Software Development",
        languages: ["HTML", "CSS", "JavaScript", "ReactJS"],
        description: "A quiz app that fetches random questions from an API and displays them to the user. Users can select how many questions they'd like (up to 50). Upon quiz submission, the app displays the user's score and correct answers. Implemented a state management system without using libraries",
    },
    
    
]

